export const SET_AWA = (value) => ({ name: "set_aspect", payload: { type: 0, value } });
export const SET_SPI = (value) => ({ name: "set_aspect", payload: { type: 1, value } });
export const SET_FIT = (value) => ({ name: "set_aspect", payload: { type: 2, value } });
export const SET_FOC = (value) => ({ name: "set_aspect", payload: { type: 3, value } });
export const SET_AWA_PERSONALITY = (value) => ({ name: "set_personality", payload: { type: 0, value } });
export const SET_SPI_PERSONALITY = (value) => ({ name: "set_personality", payload: { type: 1, value } });
export const SET_FIT_PERSONALITY = (value) => ({ name: "set_personality", payload: { type: 2, value } });
export const SET_FOC_PERSONALITY = (value) => ({ name: "set_personality", payload: { type: 3, value } });
export const ADD_BACKGROUND_CARD = (name) => ({ name: "add_card", payload: { type: "backgrounds", name } });
export const UPDATE_BACKGROUND_CARD = (id, name) => ({ name: "update_card", payload: { type: "backgrounds", id, name } });
export const REMOVE_BACKGROUND_CARD = (name) => ({ name: "remove_card", payload: { type: "backgrounds", name } });
export const ADD_SPECIALITY_CARD = (name) => ({ name: "add_card", payload: { type: "specialities", name } });
export const UPDATE_SPECIALITY_CARD = (id, name) => ({ name: "update_card", payload: { type: "specialities", id, name } });
export const REMOVE_SPECIALITY_CARD = (name) => ({ name: "remove_card", payload: { type: "specialities", name } });
export const ADD_OUTSIDE_INTEREST_CARD = (name) => ({ name: "add_card", payload: { type: "outsideInterests", name } });
export const UPDATE_OUTSIDE_INTEREST_CARD = (id, name) => ({ name: "update_card", payload: { type: "outsideInterests", id, name } });
export const REMOVE_OUTSIDE_INTEREST_CARD = (name) => ({ name: "remove_card", payload: { type: "outsideInterests", name } });
export const ADD_DISPLACED_CARD = (name) => ({ name: "add_card", payload: { type: "displaced", name } });
export const UPDATE_DISPLACED_CARD = (id, name) => ({ name: "update_card", payload: { type: "displaced", id, name } });
export const REMOVE_DISPLACED_CARD = (name) => ({ name: "remove_card", payload: { type: "displaced", name } });